export enum ActionType {
	FETCH_ALL_CANDLES = "FETCH_ALL_CANDLES",
	FETCH_CANDLE = "FETCH_CANDLE",
	CREATE_CANDLE = "CREATE_CANDLE",
	UPDATE_CANDLE = "UPDATE_CANDLE",
	DELETE_CANDLE = "DELETE_CANDLE",
	PURCHASE_CANDLE = "PURCHASE_CANDLE",
	TOGGLE_THEME = "TOGGLE_THEME",
}
