export enum ActionType {
	FETCH_ALL_CANDLES = "FETCH_ALL_CANDLES",
	FETCH_CANDLE = "FETCH_CANDLE",
	CREATE_CANDLE = "CREATE_CANDLE",
	UPDATE_CANDLE = "UPDATE_CANDLE",
	DELETE_CANDLE = "DELETE_CANDLE",
	PURCHASE_CANDLE = "PURCHASE_CANDLE",
	TOGGLE_THEME = "TOGGLE_THEME",
	CREATE_USER = "CREATE_USER",
	UPDATE_USER = "UPDATE_USER",
	GET_USER = "GET_USER",
	ADD_TO_CART = "ADD_TO_CART",
	GET_USERS_COUNT = "GET_USERS_COUNT",
}
